--- src/promptData.ts (原始)


+++ src/promptData.ts (修改后)
export const FULL_PROMPT = [
  '# MASTER PROMPT — 0-TRADER-COMPANEY: Full Project Context + Route-Mirror Exchange Build',
  '# Indonesian Paper-Trading Crypto Exchange | VPS: 187.127.178.20 | Port 22221 (new app)',
  '',
  'Paste this into BOTH Hermes agents (VPS + local). Lane split is in section F1.',
  'Project root: /home/khuchinque/0-TRADER-COMPANEY/',
  '',
  '---',
  '',
  '## PART A: PROJECT CONTEXT (What Already Exists)',
  '',
  '### A1. Project Identity',
  '- Name: 0-TRADER-COMPANEY (Trading-Crypto-Company)',
  '- Type: Paper-trading crypto venue (simulation, no real money)',
  '- Visual Reference: Bitget spot-trading terminal',
  '- Language: Indonesian flavor (Bahasa Indonesia UI)',
  '- GitHub: https://github.com/khuchinque-app/0-TRADER-COMPANEY',
  '- VPS: 187.127.178.20 (user: khuchinque)',
  '- Team: 2 developers (founder + co-developer)',
  '- Status: Phase 1 COMPLETE — Production Ready (Paper Trading)',
  '',
  '### A2. Running Services (PM2 managed)',
  '| Service | Port | Status | Description |',
  '|---------|------|--------|-------------|',
  '| Backend API | 11110 | ✅ Running | Express + Auth + Admin + FX Rate |',
  '| Terminal Frontend | 22220 | ✅ Running | Next.js dashboard |',
  '| Trading Engine | 3001 | ✅ Running | WebSocket + matching engine |',
  '| Static Files | 2217 | ✅ Running | ChinQue-Cripto design system |',
  '| NEW: Exchange | 22221 | 🔨 TO BUILD | Indodax route-mirror site |',
  '',
  '### A3. Monorepo Structure',
  '0-TRADER-COMPANEY/',
  '├── apps/',
  '│   ├── backend/              # Express API (port 11110)',
  '│   ├── engine/               # Trading engine (port 3001) + ledger.db',
  '│   ├── terminal/             # Next.js frontend (port 22220)',
  '│   └── exchange/             # 🆕 NEW APP (port 22221) — TO BUILD',
  '├── packages/',
  '│   ├── shared/               # Shared types',
  '│   ├── mexc-client/          # 🆕 MEXC public market data wrapper',
  '│   └── indodax-routes/       # 🆕 Generated route manifest',
  '├── docs/ | PLANNING/ | scripts/ | ops/',
  '├── ecosystem.config.js | docker-compose.yml | package.json',
  '',
  '### A4. Database (SQLite: apps/engine/data/ledger.db)',
  '- 21 tables: users, wallets, orders, journal (double-entry), audit_log',
  '- Enterprise: recurring_plans, deposit_addresses, withdrawal_whitelist, referrals, support_tickets, api_keys, payment_invoices, education_content',
  '- Stats: 20 users, 409 balances, 12 orders | WAL mode | All FK constraints satisfied',
  '',
  '### A5. Existing API Endpoints',
  'Backend (11110): POST /api/auth/login|register|signup|otp/verify|logout, GET /api/auth/me, GET /api/admin/stats|users|audit, CRUD /api/admin/users, POST /api/admin/users/:id/adjust, GET /health|/api/status|/api/fx-rate',
  'Engine (3001): WS /ws, GET /api/tickers|/api/market/:pair|/api/orders|/api/wallet/:userId|/api/portfolio|/api/wallet/faucet, POST /api/wallet/deposit, DELETE /api/orders/:id, GET /api/recurring/*|/api/addresses/*|/api/history/*|/api/referral/*|/api/security/*|/api/2fa/*|/api/api-keys/*|/api/education/*|/api/support/*, POST /api/payment/*',
  'Terminal (22220): / | /login | /signup | /dashboard/* | /admin/*',
  '',
  '### A6. Key Configuration',
  'PORT_BACKEND=11110, PORT_TERMINAL=22220, PORT_EXCHANGE=22221 (NEW)',
  'DB_PATH=/home/khuchinque/0-TRADER-COMPANEY/apps/engine/data/ledger.db',
  'JWT_SECRET, MARKETS=BTCUSDT,ETHUSDT,SOLUSDT,BNBUSDT,XRPUSDT, PRICE_SOURCE=sim',
  'FEE_BPS=10, SPREAD_BPS=5, STARTING_BALANCE_USDT=10000, FAUCET_AMOUNT=1000',
  'FX_SOURCE=indodax, USDT_IDR_RATE=16250 (indicative)',
  'MEXC_BASE_URL=https://api.mexc.com/api/v3 (PUBLIC ONLY — no keys)',
  'EXCHANGE_COOKIE_NAME=sx_exchange_session',
  '',
  '### A7. Admin Credentials',
  'URL: http://187.127.178.20:22220/admin/login | User: chinque | Pass: admin1',
  'Dev: chinque@dev.local / TestTrader2026!',
  '',
  '### A8. Completed Milestones (M0–M5)',
  '[x] M0-M5: System setup, Auth, Wallet, Orders, Admin, Integration',
  '[x] Enterprise Phase 1: 11 new routes + 6 new tables',
  '[x] Indodax FX rate endpoint + Design system integration',
  '[x] 183/183 vitest tests passing | 5/5 smoke tests passing',
  '',
  '### A9. Key Locked Decisions',
  '1. Paper-trading ONLY — no real money',
  '2. Internal quote = USDT; IDR is display toggle',
  '3. MVP order types = market + limit only',
  '4. Guest demo accounts with stable browser ID',
  '5. Visual reference = Bitget (3-pane layout)',
  '6. Color convention = configurable (green-up default)',
  '7. Reference data from public feeds (labeled)',
  '8. Flat fee model (10 bps fee, 5 bps spread)',
  '9. Synthetic order book from reference mid',
  '10. Indonesian market (Bahasa Indonesia UI)',
  '',
  '---',
  '',
  '## PART B: NEW BUILD — Route-Mirror Exchange on :22221',
  '',
  '### B1. Mission',
  'Add apps/exchange serving http://187.127.178.20:22221 mirroring indodax.com paths 1:1:',
  '  187.127.178.20:22221/              <-> indodax.com/',
  '  187.127.178.20:22221/market        <-> indodax.com/market',
  '  187.127.178.20:22221/market/BTCIDR <-> indodax.com/market/BTCIDR',
  '  ...all paths from sitemap',
  '- Market data from MEXC public spot API (github.com/mexcdevelop/mexc-api-sdk)',
  '- Auth/wallet/orders stay in existing backend (port 11110)',
  '- SIMULATION: virtual funds only',
  '',
  '### B2. Hard Rules',
  '1. MEXC = PUBLIC endpoints ONLY. Allowed: ping, time, exchangeInfo, depth, trades, historicalTrades, aggTrades, klines, avgPrice, ticker24hr, tickerPrice, bookTicker. FORBIDDEN: newOrder, cancelOrder, queryOrder, openOrders, allOrders, accountInfo, accountTradeList. NO MEXC API key anywhere.',
  '2. Mirror paths, NOT identity. Brand = "Simulasi Exchange". Original copy only.',
  '3. Persistent banner: "SIMULASI — dana virtual, bukan Indodax, bukan bursa sungguhan". robots.txt Disallow: / + noindex meta on every page.',
  '4. Flat layout: apps/exchange + packages/. Do not change 11110 or 22220.',
  '5. Browser NEVER calls MEXC. browser -> apps/exchange -> backend /api/market/* -> cache -> MEXC.',
  '',
  '### B3. Indodax Sitemap (fetched 2026-10-09)',
  '4 child sitemaps: homepage.xml (7 URLs), market.xml (/market/{PAIR}), depth_chart.xml (/market/depth_chart/{PAIR}), chart.xml (/chart/{PAIR})',
  '~477 pairs total (465 IDR + 12 USDT). USDT pairs: BTCUSDT, ETHUSDT, BONKUSDT, BTTUSDT, FLOKIUSDT, IDRXUSDT, LUNCUSDT, PEPEUSDT, PUNDIXUSDT, SHIBUSDT, XECUSDT, VCGUSDT.',
  'DO NOT hardcode. Generate via scripts/gen-routes.mjs -> packages/indodax-routes/routes.json',
  '',
  '### B4. Route Map',
  '/ -> / (landing + movers) | /market -> /market (all pairs table)',
  '/market/{PAIR} -> /market/{PAIR} (trading page)',
  '/market/depth_chart/{PAIR} -> /market/depth_chart/{PAIR} (depth chart)',
  '/chart/{PAIR} -> /chart/{PAIR} (full candle chart)',
  '/trade_api -> /trade_api (OUR read-only API docs)',
  '/affiliate -> /affiliate | /privacy-policy -> /privacy-policy',
  '/help/pengguna-baru | /help/ketentuan (original guides)',
  'Account paths: /akun/masuk, /akun/daftar, /akun/dompet, /akun/order',
  'States: LIVE (200) | NO_FEED (200, data-state="no-feed") | 404 (not in manifest)',
  '',
  '### B5. Pair Resolution',
  '1. Split slug: ends USDT -> quote USDT; ends IDR -> quote IDR. Strip suffix ONCE from end.',
  '   Edge cases: IDRXIDR, IDRTIDR, NEOIDRIDR, GOIDRIDR, GLIDRIDR, INDRIDR, USDTIDR, IDRXUSDT',
  '2. MEXC symbol = BASE + "USDT". Verify via exchangeInfo (refresh ~10 min).',
  '3. Internal quote = USDT. IDR display = USDT price x USDT_IDR_RATE, labeled "indikatif".',
  '4. Tradable = locked shortlist only (BTC, ETH, SOL, BNB, XRP, LINK, AAVE fallback). Rest view-only.',
  '',
  '### B6. MEXC Data Layer (packages/mexc-client)',
  'Backend routes (port 11110, all GET):',
  '  /api/market/health | /api/market/pairs | /api/market/tickers',
  '  /api/market/ticker/:slug | /api/market/depth/:slug?limit=',
  '  /api/market/trades/:slug?limit= | /api/market/klines/:slug?interval=&limit=',
  'Caching: bulk ticker24hr TTL ~2-3s, depth/trades TTL ~1s (active viewers only), klines by interval.',
  'On 429/418: exponential backoff + circuit breaker, serve stale with staleSince timestamp.',
  '',
  '### B7. Page Specs',
  '/ : hero + top movers + featured pairs + CTA to /market',
  '/market : virtualized table (~477 rows), search, quote filter, sort, favorites, sparkline, poll 3-5s',
  '/market/{PAIR} : ticker header + candle chart + order book + trade tape + order form + tabs',
  '/market/depth_chart/{PAIR} : cumulative depth (limit 500), mid marker, spread, auto-refresh',
  '/chart/{PAIR} : near-chromeless full-screen candle chart + interval selector',
  '/trade_api : docs for OUR read-only endpoints (MEXC sourced, simulated)',
  'Static pages: /affiliate, /privacy-policy, /help/pengguna-baru, /help/ketentuan (original, ID default, EN toggle)',
  '',
  '### B8. Backend Integration',
  '- Auth/wallet/orders in 11110. apps/exchange talks server-side only.',
  '- Cookie: sx_exchange_session (distinct from 22220)',
  '- Fill model: market orders walk MEXC depth; limit orders rest in our book. All fills -> ledger.db.',
  '',
  '---',
  '',
  '## PART C: MILESTONES M6–M10',
  '',
  'M6: gen-routes.mjs + routes.json; apps/exchange skeleton on 22221, all static routes 200',
  'M7: packages/mexc-client + backend /api/market/* + cache + health',
  'M8: /market and /market/{PAIR} (chart, book, tape, ticker) incl. NO_FEED and 404',
  'M9: /market/depth_chart/{PAIR}, /chart/{PAIR}, order form + wallet panel wired to backend',
  'M10: smoke script, PM2 save, RUNBOOK updated, PLANNING/LOG-exchange.md complete',
  '',
  'Acceptance (scripts/smoke-exchange.sh):',
  '  curl -sI http://187.127.178.20:22221/ -> 200',
  '  each static route -> 200',
  '  /market/BTCIDR, /market/depth_chart/BTCIDR, /chart/BTCIDR -> 200',
  '  /market/FAKEXYZ -> 404',
  '  manifest pair no MEXC -> 200 + data-state="no-feed"',
  '  /api/market/health -> ok + mexc latency',
  '  /api/market/depth/BTCIDR?limit=20 -> bids[] + asks[] non-empty',
  '  /api/market/tickers -> >0 rows, no 5xx',
  '  route parity: 0 x 5xx',
  '  grep MEXC_API_KEY|SECRET -> no matches',
  '  robots.txt -> Disallow: /',
  '',
  '---',
  '',
  '## PART D: REMAINING TODO (Original Build)',
  '',
  'Frontend pages (API exists, UI not built): recurring, authenticator, support, education, mobile-app, security, addresses, trade-api, history, referral',
  'Security (Phase 2): auth middleware, 2FA step-up, audit ray ID, Google OAuth, bcrypt, rate limits',
  'Integrations (Phase 3): WhatsApp OTP, live feeds, AI module, Duitku production',
  'Deployment (Phase 4): CI/CD, cloud deploy, backups, mobile packaging, vuln scanning',
  '',
  '---',
  '',
  '## PART E: DEPLOYMENT',
  '',
  'ssh khuchinque@187.127.178.20',
  'cd /home/khuchinque/0-TRADER-COMPANEY',
  'node scripts/gen-routes.mjs',
  'npm run build -w packages/shared',
  'npm run build --workspaces',
  'pm2 start apps/exchange/.next/server.js --name exchange -p 22221',
  'pm2 save',
  'bash scripts/smoke-exchange.sh',
  '',
  '---',
  '',
  '## PART F: LANES & LOGS',
  '',
  'VPS agent (@Herme_KhuChinQue_bot): ops/deploy — gen-routes.mjs, PM2, smoke tests, port checks',
  'Local agent (@Herme_ChinQue_bot): code — apps/exchange, packages/mexc-client, packages/indodax-routes, backend /api/market/*, docs',
  'Log: PLANNING/LOG-exchange.md, max 10 lines/milestone, format: Mx | DONE/BLOCKED | what | next',
  'Never idle; never stop before M10 acceptance passes.',
  '',
  'Defaults: separate apps/exchange app, Next.js+TS, USDT_IDR_RATE config, tradable=shortlist only, green-up theme token, all noindex, NO_FEED for unlisted pairs.',
].join('\n');
