#!/bin/bash
# VPS A2A Gateway 配置脚本
# 端口规则: 必须 >= 2000 或 >= 20000 (用户强制执行)

echo "=== VPS A2A 网关配置指南 ==="
echo ""
echo "步骤 1: 登录 VPS"
echo "  ssh root@187.127.178.20"
echo ""
echo "步骤 2: 切换到 khuchinque 用户"
echo "  su khuchinque"
echo ""
echo "步骤 3: 启动 Hermes 并配置 A2A"
echo "  hermes -p herme-khuchinque"
echo "  hermes gateway setup"
echo "  - 选择 A2A 协议"
echo "  - 端口: 29900 (符合 2xxxx 规则)"
echo ""
echo "步骤 4: 启动网关"
echo "  hermes gateway"
echo ""
echo "步骤 5: 验证"
echo "  curl http://127.0.0.1:29900/.well-known/agent-card.json"
echo ""
echo "=== 当前 VPS 端口状态 ==="
echo "  11110 - 后端 API (合规 ✓)"
echo "  22220 - 终端 Next.js (合规 ✓)"
echo "  8000  - 非合规 ✗ (需修改为 28000+)"
echo ""
echo "=== 端口规则 ==="
echo "  所有服务端口必须满足: >= 2000 或 >= 20000"
echo ""
echo "完成后，更新本地配置 ~/.hermes/profiles/herme-chinque/config.yaml:"
echo "  a2a_agents:"
echo "    hermekhu:"
echo "      url: \"http://187.127.178.20:29900/.well-known/agent-card.json\""
echo "      auth:"
echo "        type: bearer"
echo "        token: \"your-token-here\"  # 如果启用了认证"
echo "      timeout: 120"
echo "      capabilities:"
echo "        - web_search"
echo "        - terminal"
echo "        - code_execution"
echo "        - file"
echo "        - memory"
